#-------------------------------
# General Site Settings
baseURL = "https://simonroberge.com"
languageCode = "fr-ca"
title = "Simon Roberge"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 9


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3

 # [[menu.main]]
 #   identifier = "styleguide"
 #   name = "Style Guide"
 #   url = "/styleguide"
 #   weight = 4


[params]
  logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  description = "Site web de Simon Roberge"

  [params.author]
    name = "Simon Roberge"
    avatar = "/images/simon.jpg"

  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Simon Roberge"
    hero__description = "Cinéaste"
    hero__image = "/images/accueil.jpg"

  [[params.social]]
    icon = "ion-logo-vimeo"
    name = "Vimeo"
    link = "https://vimeo.com/user84907166"

 # [[params.social]]
 #   icon = "ion-logo-facebook"
 #   name = "Facebook"
 #   link = "https://facebook.com"

 # [[params.social]]
 #   icon = "ion-logo-pinterest"
 #   name = "Pinterest"
 #   link = "https://pinterest.com"

 # [[params.social]]
 #   icon = "ion-logo-dribbble"
 #   name = "Dribbble"
 #   link = "https://dribbble.com"

 # [[params.social]]
 #   icon = "ion-logo-instagram"
 #   name = "Instagram"
 #   link = "https://instagram.com"

 # [[params.social]]
 #   icon = "ion-logo-github"
 #   name = "Github"
 #   link = "https://github.com/"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/

  #-------------------------------
  # Newsletter (partials/footer-widgets/widget-subscribe.html)
  #[params.mailchimp]
  #  mailchimp__title = "Get Interesting News"
  #  mailchimp__text = "Subscribe to our newsletter and we’ll send #you the emails of latest posts."
#    mailchimp__identifier = "" # Add your MailChimp form #identifier. For example - blogenjoyfreedom.us16.list-manage.com/#subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#   mailchimp__button__text = "Subscribe" # Add your button text
#
  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "f/mwkwzkgl" # Add your email for contant form

    # NOTE
    # Aditu comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  #[params.disqus]
  #  disqusShortname = "anvod-studio-aditu" # add your shortname for #Disqus Comment. For example anvod-studio-aditu


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
